services:
  web:
    depends_on:
      api:
        condition: service_started
      tolgee:
        condition: service_healthy

  infisical:
    profiles: ["local"]

  infisical_db:
    profiles: ["local"]

  infisical_redis:
    profiles: ["local"]
