import { Injectable } from '@nestjs/common';
import { config } from '../../config/app.config';
import { ArchitectureGraphDto } from './architecture.dto';

const NODES = [
  {
    id: 'web',
    label: 'Web App (Next.js)',
    layer: 'frontend',
    kind: 'ui',
    summary: 'UI runtime, page routing, and SSR for architecture/health views.',
    x: 170,
    y: 170,
  },
  {
    id: 'rum',
    label: 'RUM Observer',
    layer: 'frontend',
    kind: 'service',
    summary: 'Captures browser vitals, errors, and navigation telemetry.',
    x: 170,
    y: 300,
  },
  {
    id: 'api',
    label: 'API (NestJS)',
    layer: 'api',
    kind: 'gateway',
    summary: 'Secure API runtime with typed config, health, metrics, and feature flags.',
    x: 430,
    y: 230,
  },
  {
    id: 'architecture-api',
    label: 'Architecture API',
    layer: 'api',
    kind: 'service',
    summary: 'Serves graph data for this visualization page.',
    x: 430,
    y: 370,
  },
  {
    id: 'feature-flags',
    label: 'Feature Flags',
    layer: 'api',
    kind: 'service',
    summary: 'Runtime toggles for optional capabilities (docs, rum ingest, etc).',
    x: 430,
    y: 500,
  },
  {
    id: 'postgres',
    label: 'Postgres (cv)',
    layer: 'data',
    kind: 'database',
    summary: 'Primary runtime data store.',
    x: 710,
    y: 200,
  },
  {
    id: 'postgres-test',
    label: 'Postgres (cv_test)',
    layer: 'data',
    kind: 'database',
    summary: 'Isolated test database for integration/e2e.',
    x: 710,
    y: 360,
  },
  {
    id: 'prometheus',
    label: 'Prometheus',
    layer: 'observability',
    kind: 'service',
    summary: 'Scrapes metrics and evaluates recording/alerting rules.',
    x: 980,
    y: 110,
  },
  {
    id: 'alertmanager',
    label: 'Alertmanager',
    layer: 'observability',
    kind: 'service',
    summary: 'Routes alerts to delivery channels (email/webhook/provider).',
    x: 980,
    y: 210,
  },
  {
    id: 'grafana',
    label: 'Grafana',
    layer: 'observability',
    kind: 'ui',
    summary: 'Dashboards across metrics and logs.',
    x: 980,
    y: 310,
  },
  {
    id: 'loki',
    label: 'Loki',
    layer: 'observability',
    kind: 'service',
    summary: 'Log storage/query backend.',
    x: 980,
    y: 410,
  },
  {
    id: 'otel',
    label: 'OTel Collector',
    layer: 'observability',
    kind: 'service',
    summary: 'Trace pipeline from API to Jaeger.',
    x: 980,
    y: 510,
  },
  {
    id: 'jaeger',
    label: 'Jaeger',
    layer: 'observability',
    kind: 'ui',
    summary: 'Trace search and span-level inspection UI.',
    x: 980,
    y: 610,
  },
  {
    id: 'ci-quality',
    label: 'CI Quality',
    layer: 'delivery',
    kind: 'pipeline',
    summary: 'Lint, typecheck, build, and API coverage gate.',
    x: 160,
    y: 620,
  },
  {
    id: 'ci-int-e2e',
    label: 'CI Integration + E2E',
    layer: 'delivery',
    kind: 'pipeline',
    summary: 'DB migration, integration/e2e tests, k6 smoke, contract drift.',
    x: 360,
    y: 680,
  },
  {
    id: 'ci-security',
    label: 'CI Security',
    layer: 'delivery',
    kind: 'pipeline',
    summary: 'Audit, image scan (Trivy), SBOM (Syft), and secrets scan.',
    x: 620,
    y: 680,
  },
  {
    id: 'ci-web-smoke',
    label: 'CI Web Smoke',
    layer: 'delivery',
    kind: 'pipeline',
    summary: 'Playwright smoke test against dockerized web + api.',
    x: 840,
    y: 680,
  },
] as const;

const EDGES = [
  { from: 'web', to: 'api', relation: 'calls' },
  { from: 'web', to: 'architecture-api', relation: 'calls' },
  { from: 'rum', to: 'api', relation: 'sends events' },
  { from: 'architecture-api', to: 'feature-flags', relation: 'reads config' },
  { from: 'api', to: 'postgres', relation: 'reads/writes' },
  { from: 'ci-int-e2e', to: 'postgres-test', relation: 'migrates/tests' },
  { from: 'api', to: 'prometheus', relation: 'exposes /metrics' },
  { from: 'api', to: 'otel', relation: 'exports traces' },
  { from: 'otel', to: 'jaeger', relation: 'ships traces' },
  { from: 'api', to: 'loki', relation: 'ships logs via promtail' },
  { from: 'prometheus', to: 'alertmanager', relation: 'fires alerts' },
  { from: 'prometheus', to: 'grafana', relation: 'datasource' },
  { from: 'loki', to: 'grafana', relation: 'datasource' },
  { from: 'ci-quality', to: 'api', relation: 'lint/type/build/test:cov' },
  { from: 'ci-int-e2e', to: 'api', relation: 'int/e2e/k6' },
  { from: 'ci-int-e2e', to: 'architecture-api', relation: 'openapi contract check' },
  { from: 'ci-security', to: 'api', relation: 'scan image/deps' },
  { from: 'ci-security', to: 'web', relation: 'scan image/deps' },
  { from: 'ci-web-smoke', to: 'web', relation: 'playwright smoke' },
] as const;

@Injectable()
export class ArchitectureService {
  getGraph(): ArchitectureGraphDto {
    return {
      version: '2026.02',
      generatedAt: new Date().toISOString(),
      layers: ['frontend', 'api', 'data', 'observability', 'delivery'],
      featureFlags: { ...config.features },
      nodes: [...NODES],
      edges: [...EDGES],
      stats: {
        nodeCount: NODES.length,
        edgeCount: EDGES.length,
      },
    };
  }
}
