#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT_DIR/docker/promtail/relabel-service.yml"

mkdir -p "$(dirname "$OUT")"

api_id="$(docker inspect -f '{{.Id}}' "$(docker compose -f "$ROOT_DIR/docker/compose.yml" ps -q api)")"
web_id="$(docker inspect -f '{{.Id}}' "$(docker compose -f "$ROOT_DIR/docker/compose.yml" ps -q web)")"
pg_id="$(docker inspect -f '{{.Id}}' "$(docker compose -f "$ROOT_DIR/docker/compose.yml" ps -q postgres)")"

cat > "$OUT" <<EOF
# Generated by scripts/promtail-map.sh — DO NOT EDIT
- source_labels: ['container_id']
  regex: '$api_id'
  target_label: service
  replacement: 'api'
- source_labels: ['container_id']
  regex: '$web_id'
  target_label: service
  replacement: 'web'
- source_labels: ['container_id']
  regex: '$pg_id'
  target_label: service
  replacement: 'postgres'
EOF

echo "Wrote $OUT"